### ISSUE TITLE
Unable to find instances of Text Crop components

### ISSUE THREAD

**Issue by georgialoper** [LukeFinch/Figma-Text-Crop#10]
Seems like the plugin is unable to recognize instances of the Text Crop component

## Steps to reproduce
1. Select "Auto height"
<img width="359" alt="Screen Shot 2022-03-30 at 1 22 16 PM" src="https://user-images.githubusercontent.com/22507118/160894881-b8d8429c-94e0-4013-9a80-46217ca79682.png">

2a. Selecting "Crop Selected" from the "Plugins" section of the design panel
<img width="406" alt="Screen Shot 2022-03-30 at 1 22 03 PM" src="https://user-images.githubusercontent.com/22507118/160895321-ca9c34dc-070f-4cad-8d5b-ded3e9f2e70a.png">

2b. Selecting "Crop Selected from the rt click + Drop Down menu
<img width="829" alt="Screen Shot 2022-03-30 at 1 22 53 PM" src="https://user-images.githubusercontent.com/22507118/160895480-c440ae31-eaaa-462e-93a7-c13a9a9191dc.png">

---

Seems like checking for `(n.type =="COMPONENT")` instead of `INSTANCE` in `code.ts` solves the issue.
<img width="313" alt="Screen Shot 2022-03-30 at 1 29 02 PM" src="https://user-images.githubusercontent.com/22507118/160896341-483a45c7-0731-426c-9202-ffa9938bb904.png">
<img width="398" alt="Screen Shot 2022-03-30 at 1 32 29 PM" src="https://user-images.githubusercontent.com/22507118/160896312-c7384bf3-6fc1-4070-b0d2-309047973e0f.png">

I'm not very familiar with figma plugins to know what might have changed or what might be impacted by updating this

**Comment by LukeFinch** [comment]
Ah, thanks for this feedback Georgia!

I hadn't intended for the base components themselves to be cropped, but there's a good reason as to why you'd want to do that. 

I'll push a fix when I get a chance

**Comment by georgialoper** [comment]
I just used these base components as an example - it's also not picking up on any instances when I drop my own text in

**Comment by LukeFinch** [comment]
Interesting. I just put a new branch up called fix-components, do you mind trying that and seeing if it works for you?

**Comment by georgialoper** [comment]
That worked!

**Comment by LukeFinch** [comment]
Sweet, just got to run some other tests and make sure everything is as expected, before publishing it.
I'll keep this issue open for now in case you run into any issues running on the dev version for the time being.

**Comment by georgialoper** [comment]
Hey Luke, is there anything I can help with to get this ready to publish?

**Comment by LukeFinch** [comment]
Hey Georgia!
A busy couple of weeks for me sorry. Will do it now :) 
Assuming you've had no problems with the dev version?

**Comment by georgialoper** [comment]
Nope, at least it seems to work for my use case

**Comment by LukeFinch** [comment]
Just published now.
Thanks for your feedback Georgia
